"""fix on_delete

Revision ID: 353b1ca6f2cd
Revises: 37e28fe0e071
Create Date: 2024-02-06 05:29:34.262772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353b1ca6f2cd'
down_revision: Union[str, None] = '37e28fe0e071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'todo', type_='foreignkey')
    # op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    # バッチモードを使用して古い制約を削除します
    with op.batch_alter_table('todo') as batch_op:
        batch_op.drop_constraint(None, 'foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
